name: Build artifacts

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  workflow_dispatch:
env:
  GHCR_SLUG: ghcr.io/ledfx/ledfx_v3
  PLATFORMS: linux/amd64,linux/arm64
  BINARY_NAME: LedFx-${{ matrix.os }}-${{ matrix.arch }}


jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: macos-latest
            name: Macos-Build AMD64
            os: darwin
            arch: amd64

          - runner: macos-latest
            name: Macos-Build ARM64
            os: darwin
            arch: ARM64

          - runner: ubuntu-latest
            name: Linux-Build AMD64
            platform: linux/amd64
            os: linux
            arch: amd64
            
          - runner: ubuntu-latest
            name: Linux-Build ARM64
            platform: linux/arm64
            os: linux
            arch: arm64
                        
          - runner: ubuntu-latest
            name: Linux-Build armhf
            platform: linux/arm/v7
            os: armhf
            arch: arm64
                    
          - runner: ubuntu-latest
            name: Linux-Build armel
            platform: linux/arm/v6
            os: linux
            arch: armel
                           
          - runner: windows-latest
            name: Windows-Build AMD64
            os: windows
            arch: amd64
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Write Env
      run: |
        env
        printenv > $BINARY_NAME

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BINARY_NAME }}-${{ github.sha }}