# I am a workflow that demonstrates how to output the different context objects

name: Variables and Context Macos

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

env:
  VAR1: myworkflowvar1
  VAR2: myworkflowvar2
  VAR3: myworkflowvar3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job1:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -x {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Check out code from GitHub
        uses: actions/checkout@v4
        with:
          repository: LedFx/LedFx
          ref: main
          
      - name: Install poetry
        id: instal-poetry
        # run: echo "::set-output name=step2value::world"
        run: |
          pipx install poetry
        
      - name: Configure poetry
        id: configure-poetry
        run: poetry config virtualenvs.in-project true 
        
      - name: Check poetry env
        id: check-env
        # run: echo "::set-output name=step2value::world"
        run: |
          poetry env info
      - name: Build wheel for ledfx
        id: build-ledfx
        # run: echo "::set-output name=step2value::world"
        run: |
          poetry build
      - name: Install ledfx
        id: install-ledfx
        # run: echo "::set-output name=step2value::world"
        run: |
          poetry install
          
